// frontend/src/app/dashboard/page.tsx
'use client';

import React from 'react';
import {
  Grid,
  Card,
  CardContent,
  Typography,
  Box,
  Button,
  Paper,
} from '@mui/material';
import {
  Business as BusinessIcon,
  Assignment as AssignmentIcon,
  Assessment as AssessmentIcon,
  Add as AddIcon,
} from '@mui/icons-material';
import { useRouter } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import apiClient from '@/api/client';
import Layout from '@/components/Layout';
import AuthGuard from '@/components/AuthGuard';

interface WorkEntryData {
  id: number;
  client_name: string;
  hours: number;
  date: string;
  description?: string;
}

export default function DashboardPage() {
  const router = useRouter();

  const { data: clientsData } = useQuery({
    queryKey: ['clients'],
    queryFn: () => apiClient.getClients(),
  });

  const { data: workEntriesData } = useQuery({
    queryKey: ['workEntries'],
    queryFn: () => apiClient.getWorkEntries(),
  });

  const clients = clientsData?.clients || [];
  const workEntries = workEntriesData?.workEntries || [];

  const totalHours = workEntries.reduce((sum: number, entry: { hours: number }) => sum + entry.hours, 0);
  const recentEntries = workEntries.slice(0, 5);

  const statsCards = [
    {
      title: 'Total Clients',
      value: clients.length,
      icon: <BusinessIcon />,
      color: '#1976d2',
      action: () => router.push('/clients'),
    },
    {
      title: 'Total Work Entries',
      value: workEntries.length,
      icon: <AssignmentIcon />,
      color: '#388e3c',
      action: () => router.push('/work-entries'),
    },
    {
      title: 'Total Hours',
      value: totalHours.toFixed(2),
      icon: <AssessmentIcon />,
      color: '#f57c00',
      action: () => router.push('/reports'),
    },
  ];

  return (
    <AuthGuard>
      <Layout>
        <Box>
          <Typography variant="h4" gutterBottom>
            Dashboard
          </Typography>

          <Grid container spacing={3} sx={{ mb: 4 }}>
            {statsCards.map((stat, index) => (
              <Grid size={{ xs: 12, sm: 6, md: 4 }} key={index}>
                <Card
                  sx={{
                    cursor: 'pointer',
                    transition: 'transform 0.2s',
                    '&:hover': {
                      transform: 'translateY(-4px)',
                    },
                  }}
                  onClick={stat.action}
                >
                  <CardContent>
                    <Box display="flex" alignItems="center" justifyContent="space-between" gap={3}>
                      <Box>
                        <Typography color="textSecondary" gutterBottom variant="h6">
                          {stat.title}
                        </Typography>
                        <Typography variant="h4" component="div">
                          {stat.value}
                        </Typography>
                      </Box>
                      <Box
                        sx={{
                          backgroundColor: stat.color,
                          borderRadius: 1,
                          p: 1,
                          color: 'white',
                          flexShrink: 0,
                        }}
                      >
                        {stat.icon}
                      </Box>
                    </Box>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>

          <Grid container spacing={3}>
            <Grid size={{ xs: 12, md: 8 }}>
              <Paper sx={{ p: 3 }}>
                <Box display="flex" justifyContent="space-between" alignItems="center" mb={2} gap={3}>
                  <Typography variant="h6">Recent Work Entries</Typography>
                  <Button
                    variant="outlined"
                    startIcon={<AddIcon />}
                    onClick={() => router.push('/work-entries')}
                    sx={{ flexShrink: 0 }}
                  >
                    Add Entry
                  </Button>
                </Box>
                {recentEntries.length > 0 ? (
                  recentEntries.map((entry: WorkEntryData) => (
                    <Box key={entry.id} sx={{ mb: 2, pb: 2, borderBottom: '1px solid #eee' }}>
                      <Typography variant="subtitle1">{entry.client_name}</Typography>
                      <Typography variant="body2" color="text.secondary">
                        {entry.hours} hours - {new Date(entry.date).toLocaleDateString()}
                      </Typography>
                      {entry.description && (
                        <Typography variant="body2" sx={{ mt: 1 }}>
                          {entry.description}
                        </Typography>
                      )}
                    </Box>
                  ))
                ) : (
                  <Typography color="text.secondary">No work entries yet</Typography>
                )}
              </Paper>
            </Grid>

            <Grid size={{ xs: 12, md: 4 }}>
              <Paper sx={{ p: 3 }}>
                <Typography variant="h6" mb={2}>
                  Quick Actions
                </Typography>
                <Box display="flex" flexDirection="column" gap={2}>
                  <Button
                    variant="contained"
                    startIcon={<AddIcon />}
                    onClick={() => router.push('/clients')}
                    fullWidth
                  >
                    Add Client
                  </Button>
                  <Button
                    variant="contained"
                    startIcon={<AddIcon />}
                    onClick={() => router.push('/work-entries')}
                    fullWidth
                  >
                    Add Work Entry
                  </Button>
                  <Button
                    variant="outlined"
                    startIcon={<AssessmentIcon />}
                    onClick={() => router.push('/reports')}
                    fullWidth
                  >
                    View Reports
                  </Button>
                </Box>
              </Paper>
            </Grid>
          </Grid>
        </Box>
      </Layout>
    </AuthGuard>
  );
}

// frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ApiService } from '../../services/api.service';
import { Client, WorkEntry } from '../../models/api.models';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule
  ],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  clients: Client[] = [];
  workEntries: WorkEntry[] = [];
  isLoading = true;

  constructor(
    private apiService: ApiService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.isLoading = true;
    
    this.apiService.getClients().subscribe({
      next: (response) => {
        this.clients = response.clients || [];
      },
      error: (err) => console.error('Failed to load clients:', err)
    });

    this.apiService.getWorkEntries().subscribe({
      next: (response) => {
        this.workEntries = response.workEntries || [];
        this.isLoading = false;
      },
      error: (err) => {
        console.error('Failed to load work entries:', err);
        this.isLoading = false;
      }
    });
  }

  get totalHours(): number {
    return this.workEntries.reduce((sum, entry) => sum + entry.hours, 0);
  }

  get recentEntries(): WorkEntry[] {
    return this.workEntries.slice(0, 5);
  }

  navigateTo(path: string): void {
    this.router.navigate([path]);
  }
}

<div class="dashboard-container">
  <h1>Dashboard</h1>

  <div class="stats-grid" *ngIf="!isLoading">
    <mat-card class="stat-card" (click)="navigateTo('/clients')">
      <mat-card-content>
        <div class="stat-content">
          <div class="stat-info">
            <h3>Total Clients</h3>
            <span class="stat-value">{{ clients.length }}</span>
          </div>
          <div class="stat-icon" style="background-color: #1976d2;">
            <mat-icon>business</mat-icon>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <mat-card class="stat-card" (click)="navigateTo('/work-entries')">
      <mat-card-content>
        <div class="stat-content">
          <div class="stat-info">
            <h3>Total Work Entries</h3>
            <span class="stat-value">{{ workEntries.length }}</span>
          </div>
          <div class="stat-icon" style="background-color: #388e3c;">
            <mat-icon>assignment</mat-icon>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <mat-card class="stat-card" (click)="navigateTo('/reports')">
      <mat-card-content>
        <div class="stat-content">
          <div class="stat-info">
            <h3>Total Hours</h3>
            <span class="stat-value">{{ totalHours.toFixed(2) }}</span>
          </div>
          <div class="stat-icon" style="background-color: #f57c00;">
            <mat-icon>assessment</mat-icon>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>

  <div class="content-grid" *ngIf="!isLoading">
    <mat-card class="recent-entries">
      <mat-card-header>
        <mat-card-title>
          <div class="card-header">
            <h2>Recent Work Entries</h2>
            <button mat-stroked-button (click)="navigateTo('/work-entries')">
              <mat-icon>add</mat-icon>
              Add Entry
            </button>
          </div>
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div *ngIf="recentEntries.length > 0">
          <div class="entry-item" *ngFor="let entry of recentEntries">
            <h4>{{ entry.client_name }}</h4>
            <p class="entry-meta">{{ entry.hours }} hours - {{ entry.date | date:'shortDate' }}</p>
            <p class="entry-description" *ngIf="entry.description">{{ entry.description }}</p>
          </div>
        </div>
        <p class="no-data" *ngIf="recentEntries.length === 0">No work entries yet</p>
      </mat-card-content>
    </mat-card>

    <mat-card class="quick-actions">
      <mat-card-header>
        <mat-card-title>
          <h2>Quick Actions</h2>
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="actions-list">
          <button mat-raised-button color="primary" (click)="navigateTo('/clients')">
            <mat-icon>add</mat-icon>
            Add Client
          </button>
          <button mat-raised-button color="primary" (click)="navigateTo('/work-entries')">
            <mat-icon>add</mat-icon>
            Add Work Entry
          </button>
          <button mat-stroked-button color="primary" (click)="navigateTo('/reports')">
            <mat-icon>assessment</mat-icon>
            View Reports
          </button>
        </div>
      </mat-card-content>
    </mat-card>
  </div>

  <div class="loading-container" *ngIf="isLoading">
    <mat-spinner></mat-spinner>
  </div>
</div>
