// frontend/src/app/reports/page.tsx
'use client';

import React, { useState } from 'react';
import {
  Box,
  Typography,
  Button,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Card,
  CardContent,
  Grid,
  Alert,
  CircularProgress,
  Chip,
  IconButton,
  Tooltip,
} from '@mui/material';
import {
  PictureAsPdf as PdfIcon,
  Description as CsvIcon,
} from '@mui/icons-material';
import { useQuery } from '@tanstack/react-query';
import apiClient from '@/api/client';
import { type ClientReport } from '@/types/api';
import Layout from '@/components/Layout';
import AuthGuard from '@/components/AuthGuard';

export default function ReportsPage() {
  const [selectedClientId, setSelectedClientId] = useState<number>(0);
  const [error, setError] = useState('');

  const { data: clientsData, isLoading: clientsLoading } = useQuery({
    queryKey: ['clients'],
    queryFn: () => apiClient.getClients(),
  });

  const { data: reportData, isLoading: reportLoading } = useQuery({
    queryKey: ['clientReport', selectedClientId],
    queryFn: () => apiClient.getClientReport(selectedClientId),
    enabled: selectedClientId > 0,
  });

  const clients = clientsData?.clients || [];
  const report = reportData as ClientReport | undefined;

  const handleExportCsv = async () => {
    if (!selectedClientId) return;
    
    try {
      const blob = await apiClient.exportClientReportCsv(selectedClientId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const client = clients.find((c: { id: number; name: string }) => c.id === selectedClientId);
      a.download = `${client?.name?.replace(/[^a-zA-Z0-9]/g, '_')}_report_${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: unknown) {
      setError('Failed to export CSV report');
      console.error('Export error:', err);
    }
  };

  const handleExportPdf = async () => {
    if (!selectedClientId) return;

    try {
      const blob = await apiClient.exportClientReportPdf(selectedClientId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const client = clients.find((c: { id: number; name: string }) => c.id === selectedClientId);
      a.download = `${client?.name?.replace(/[^a-zA-Z0-9]/g, '_')}_report_${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: unknown) {
      setError('Failed to export PDF report');
      console.error('Export error:', err);
    }
  };

  const selectedClient = clients.find((c: { id: number; name: string }) => c.id === selectedClientId);

  if (clientsLoading) {
    return (
      <AuthGuard>
        <Layout>
          <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
            <CircularProgress />
          </Box>
        </Layout>
      </AuthGuard>
    );
  }

  return (
    <AuthGuard>
      <Layout>
        <Box>
          <Typography variant="h4" gutterBottom>
            Reports
          </Typography>

          {error && (
            <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>
              {error}
            </Alert>
          )}

          {clients.length === 0 ? (
            <Paper sx={{ p: 3, textAlign: 'center' }}>
              <Typography color="text.secondary" sx={{ mb: 2 }}>
                You need to create at least one client before generating reports.
              </Typography>
              <Button variant="contained" href="/clients">
                Create Client
              </Button>
            </Paper>
          ) : (
            <>
              <Paper sx={{ p: 3, mb: 3 }}>
                <Grid container spacing={3} alignItems="center">
                  <Grid size={{ xs: 12, md: 6 }}>
                    <FormControl fullWidth>
                      <InputLabel>Select Client</InputLabel>
                      <Select
                        value={selectedClientId}
                        onChange={(e) => setSelectedClientId(Number(e.target.value))}
                        label="Select Client"
                      >
                        <MenuItem value={0}>Choose a client...</MenuItem>
                        {clients.map((c: { id: number; name: string }) => (
                          <MenuItem key={c.id} value={c.id}>
                            {c.name}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>
                  </Grid>
                  <Grid size={{ xs: 12, md: 6 }}>
                    <Box display="flex" gap={2}>
                      <Tooltip title="Export as CSV">
                        <IconButton
                          onClick={handleExportCsv}
                          disabled={!selectedClientId || reportLoading}
                          color="primary"
                          size="large"
                        >
                          <CsvIcon />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Export as PDF">
                        <IconButton
                          onClick={handleExportPdf}
                          disabled={!selectedClientId || reportLoading}
                          color="error"
                          size="large"
                        >
                          <PdfIcon />
                        </IconButton>
                      </Tooltip>
                    </Box>
                  </Grid>
                </Grid>
              </Paper>

              {selectedClient && reportLoading && (
                <Box display="flex" justifyContent="center" alignItems="center" minHeight="200px">
                  <CircularProgress />
                </Box>
              )}

              {selectedClient && report && (
                <>
                  <Grid container spacing={3} sx={{ mb: 3 }}>
                    <Grid size={{ xs: 12, sm: 6, md: 4 }}>
                      <Card>
                        <CardContent>
                          <Typography color="textSecondary" gutterBottom>
                            Total Hours
                          </Typography>
                          <Typography variant="h4" component="div">
                            {report.totalHours.toFixed(2)}
                          </Typography>
                        </CardContent>
                      </Card>
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6, md: 4 }}>
                      <Card>
                        <CardContent>
                          <Typography color="textSecondary" gutterBottom>
                            Total Entries
                          </Typography>
                          <Typography variant="h4" component="div">
                            {report.entryCount}
                          </Typography>
                        </CardContent>
                      </Card>
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6, md: 4 }}>
                      <Card>
                        <CardContent>
                          <Typography color="textSecondary" gutterBottom>
                            Average Hours per Entry
                          </Typography>
                          <Typography variant="h4" component="div">
                            {report.entryCount > 0 ? (report.totalHours / report.entryCount).toFixed(2) : '0.00'}
                          </Typography>
                        </CardContent>
                      </Card>
                    </Grid>
                  </Grid>

                  <Paper>
                    <TableContainer>
                      <Table>
                        <TableHead>
                          <TableRow>
                            <TableCell>Date</TableCell>
                            <TableCell>Hours</TableCell>
                            <TableCell>Description</TableCell>
                            <TableCell>Created</TableCell>
                          </TableRow>
                        </TableHead>
                        <TableBody>
                          {report.workEntries.length > 0 ? (
                            report.workEntries.map((entry) => (
                              <TableRow key={entry.id}>
                                <TableCell>
                                  <Typography variant="body2">
                                    {new Date(entry.date).toLocaleDateString()}
                                  </Typography>
                                </TableCell>
                                <TableCell>
                                  <Chip 
                                    label={`${entry.hours} hours`} 
                                    color="primary" 
                                    variant="outlined" 
                                  />
                                </TableCell>
                                <TableCell>
                                  {entry.description ? (
                                    <Typography variant="body2" color="text.secondary">
                                      {entry.description}
                                    </Typography>
                                  ) : (
                                    <Chip label="No description" size="small" variant="outlined" />
                                  )}
                                </TableCell>
                                <TableCell>
                                  <Typography variant="body2" color="text.secondary">
                                    {new Date(entry.created_at).toLocaleDateString()}
                                  </Typography>
                                </TableCell>
                              </TableRow>
                            ))
                          ) : (
                            <TableRow>
                              <TableCell colSpan={4} align="center">
                                <Typography color="text.secondary" sx={{ py: 3 }}>
                                  No work entries found for this client.
                                </Typography>
                              </TableCell>
                            </TableRow>
                          )}
                        </TableBody>
                      </Table>
                    </TableContainer>
                  </Paper>
                </>
              )}

              {!selectedClient && (
                <Paper sx={{ p: 3, textAlign: 'center' }}>
                  <Typography color="text.secondary">
                    Select a client to view their time report.
                  </Typography>
                </Paper>
              )}
            </>
          )}
        </Box>
      </Layout>
    </AuthGuard>
  );
}

// frontend/src/app/pages/reports/reports.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatChipsModule } from '@angular/material/chips';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ApiService } from '../../services/api.service';
import { Client, ClientReport, WorkEntry } from '../../models/api.models';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatTooltipModule
  ],
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.scss']
})
export class ReportsComponent implements OnInit {
  clients: Client[] = [];
  selectedClientId = 0;
  report: ClientReport | null = null;
  isLoading = true;
  reportLoading = false;
  error = '';
  displayedColumns = ['date', 'hours', 'description', 'created'];

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadClients();
  }

  loadClients(): void {
    this.isLoading = true;
    this.apiService.getClients().subscribe({
      next: (response) => {
        this.clients = response.clients || [];
        this.isLoading = false;
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to load clients';
        this.isLoading = false;
      }
    });
  }

  onClientChange(): void {
    if (this.selectedClientId > 0) {
      this.loadReport();
    } else {
      this.report = null;
    }
  }

  loadReport(): void {
    this.reportLoading = true;
    this.apiService.getClientReport(this.selectedClientId).subscribe({
      next: (response) => {
        this.report = response;
        this.reportLoading = false;
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to load report';
        this.reportLoading = false;
      }
    });
  }

  exportCsv(): void {
    if (!this.selectedClientId) return;

    this.apiService.exportClientReportCsv(this.selectedClientId).subscribe({
      next: (blob) => {
        this.downloadFile(blob, 'csv');
      },
      error: () => {
        this.error = 'Failed to export CSV report';
      }
    });
  }

  exportPdf(): void {
    if (!this.selectedClientId) return;

    this.apiService.exportClientReportPdf(this.selectedClientId).subscribe({
      next: (blob) => {
        this.downloadFile(blob, 'pdf');
      },
      error: () => {
        this.error = 'Failed to export PDF report';
      }
    });
  }

  private downloadFile(blob: Blob, type: 'csv' | 'pdf'): void {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const client = this.clients.find(c => c.id === this.selectedClientId);
    const clientName = client?.name?.replace(/[^a-zA-Z0-9]/g, '_') || 'report';
    const date = new Date().toISOString().split('T')[0];
    a.download = `${clientName}_report_${date}.${type}`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }

  get averageHoursPerEntry(): number {
    if (!this.report || this.report.entryCount === 0) return 0;
    return this.report.totalHours / this.report.entryCount;
  }

  clearError(): void {
    this.error = '';
  }
}

<div class="reports-container">
  <h1>Reports</h1>

  <div class="error-alert" *ngIf="error" (click)="clearError()">
    <mat-icon>error</mat-icon>
    <span>{{ error }}</span>
    <mat-icon class="close-icon">close</mat-icon>
  </div>

  <mat-card *ngIf="!isLoading && clients.length === 0" class="no-clients-card">
    <mat-card-content>
      <p>You need to create at least one client before generating reports.</p>
      <a mat-raised-button color="primary" routerLink="/clients">Create Client</a>
    </mat-card-content>
  </mat-card>

  <div *ngIf="!isLoading && clients.length > 0">
    <mat-card class="filter-card">
      <mat-card-content>
        <div class="filter-row">
          <mat-form-field appearance="outline" class="client-select">
            <mat-label>Select Client</mat-label>
            <mat-select [(ngModel)]="selectedClientId" (selectionChange)="onClientChange()">
              <mat-option [value]="0">Choose a client...</mat-option>
              <mat-option *ngFor="let client of clients" [value]="client.id">
                {{ client.name }}
              </mat-option>
            </mat-select>
          </mat-form-field>

          <div class="export-buttons">
            <button mat-icon-button color="primary" matTooltip="Export as CSV" 
                    (click)="exportCsv()" [disabled]="!selectedClientId || reportLoading">
              <mat-icon>description</mat-icon>
            </button>
            <button mat-icon-button color="warn" matTooltip="Export as PDF" 
                    (click)="exportPdf()" [disabled]="!selectedClientId || reportLoading">
              <mat-icon>picture_as_pdf</mat-icon>
            </button>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <div class="loading-container" *ngIf="reportLoading">
      <mat-spinner></mat-spinner>
    </div>

    <div *ngIf="report && !reportLoading">
      <div class="stats-grid">
        <mat-card class="stat-card">
          <mat-card-content>
            <h3>Total Hours</h3>
            <span class="stat-value">{{ report.totalHours.toFixed(2) }}</span>
          </mat-card-content>
        </mat-card>

        <mat-card class="stat-card">
          <mat-card-content>
            <h3>Total Entries</h3>
            <span class="stat-value">{{ report.entryCount }}</span>
          </mat-card-content>
        </mat-card>

        <mat-card class="stat-card">
          <mat-card-content>
            <h3>Average Hours per Entry</h3>
            <span class="stat-value">{{ averageHoursPerEntry.toFixed(2) }}</span>
          </mat-card-content>
        </mat-card>
      </div>

      <mat-card>
        <table mat-table [dataSource]="report.workEntries" class="full-width">
          <ng-container matColumnDef="date">
            <th mat-header-cell *matHeaderCellDef>Date</th>
            <td mat-cell *matCellDef="let entry">
              {{ entry.date | date:'shortDate' }}
            </td>
          </ng-container>

          <ng-container matColumnDef="hours">
            <th mat-header-cell *matHeaderCellDef>Hours</th>
            <td mat-cell *matCellDef="let entry">
              <mat-chip color="primary">{{ entry.hours }} hours</mat-chip>
            </td>
          </ng-container>

          <ng-container matColumnDef="description">
            <th mat-header-cell *matHeaderCellDef>Description</th>
            <td mat-cell *matCellDef="let entry">
              <span *ngIf="entry.description">{{ entry.description }}</span>
              <mat-chip *ngIf="!entry.description">No description</mat-chip>
            </td>
          </ng-container>

          <ng-container matColumnDef="created">
            <th mat-header-cell *matHeaderCellDef>Created</th>
            <td mat-cell *matCellDef="let entry">
              {{ entry.created_at | date:'shortDate' }}
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

          <tr class="mat-row" *matNoDataRow>
            <td class="mat-cell no-data" [attr.colspan]="displayedColumns.length">
              No work entries found for this client.
            </td>
          </tr>
        </table>
      </mat-card>
    </div>

    <mat-card *ngIf="!selectedClientId && !reportLoading" class="select-client-card">
      <mat-card-content>
        <p>Select a client to view their time report.</p>
      </mat-card-content>
    </mat-card>
  </div>

  <div class="loading-container" *ngIf="isLoading">
    <mat-spinner></mat-spinner>
  </div>
</div>
